FUNCTION ARGUMENTS:
	DEFAULT ARGUMETS


$ cat test.py 
#!/usr/bin/python

#INITIALIZE THE FUNCTION

def function_name(name,age):
	"The cahnges a passed list into this function..."
	print("Print the name as: ", name)
	print("Print the age of man as: ", age)
	return

#CALLING THE FUNCTION
function_name(age=23,name='Ali');

function_name(name="Alam")

O/P:

$ ./test.py 
('Print the name as: ', 'Ali')
('Print the age of man as: ', 23)
Traceback (most recent call last):
  File "./test.py", line 14, in <module>
    function_name(name="Alam")
TypeError: function_name() takes exactly 2 arguments (1 given)

OR

$ cat test.py 
#!/usr/bin/python

#INITIALIZE THE FUNCTION

def function_name(name,age):
	"The cahnges a passed list into this function..."
	print("Print the name as: ", name)
	print("Print the age of man as: ", age)
	return

#CALLING THE FUNCTION
function_name(age=23,name='Ali');

#DEFAULT ARGUMENT CONCEPT IS NOT WORKING
#function_name(name="Alam")

