// here we passed the argument is being overwritten by reference and the reference is being overwritten inside the called function.

cat test.py 
#!/usr/bin/python

# INITIALIZE THE FUNCTION

def function_name(myList):
	"The changes a passed list into this function.. "
	myList=[10,20,30,40,50]
	print("Values inside the function", myList)
	return 

# CALL THE function_name

myList=[33,44,555];
function_name(myList);
print("Values outside the function: ", myList)

O/P:

./test.py 
('Values inside the function', [10, 20, 30, 40, 50])
('Values outside the function: ', [33, 44, 555])
